/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiOutreachRouteImport } from './routes/api/outreach'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiWebhooksSubscribeRouteImport } from './routes/api/webhooks/subscribe'
import { Route as ApiLeadsSyncRouteImport } from './routes/api/leads.sync'
import { Route as ApiDashboardMetricsRouteImport } from './routes/api/dashboard/metrics'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthSigninRouteImport } from './routes/api/auth/signin'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutreachRoute = ApiOutreachRouteImport.update({
  id: '/api/outreach',
  path: '/api/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSubscribeRoute = ApiWebhooksSubscribeRouteImport.update({
  id: '/api/webhooks/subscribe',
  path: '/api/webhooks/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsSyncRoute = ApiLeadsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiDashboardMetricsRoute = ApiDashboardMetricsRouteImport.update({
  id: '/api/dashboard/metrics',
  path: '/api/dashboard/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/upload': typeof UploadRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/outreach': typeof ApiOutreachRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/leads/sync': typeof ApiLeadsSyncRoute
  '/api/webhooks/subscribe': typeof ApiWebhooksSubscribeRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/upload': typeof UploadRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/outreach': typeof ApiOutreachRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/leads/sync': typeof ApiLeadsSyncRoute
  '/api/webhooks/subscribe': typeof ApiWebhooksSubscribeRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/upload': typeof UploadRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/outreach': typeof ApiOutreachRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/dashboard/metrics': typeof ApiDashboardMetricsRoute
  '/api/leads/sync': typeof ApiLeadsSyncRoute
  '/api/webhooks/subscribe': typeof ApiWebhooksSubscribeRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/upload'
    | '/api/leads'
    | '/api/outreach'
    | '/api/upload'
    | '/api/auth/signin'
    | '/api/auth/signup'
    | '/api/dashboard/metrics'
    | '/api/leads/sync'
    | '/api/webhooks/subscribe'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/upload'
    | '/api/leads'
    | '/api/outreach'
    | '/api/upload'
    | '/api/auth/signin'
    | '/api/auth/signup'
    | '/api/dashboard/metrics'
    | '/api/leads/sync'
    | '/api/webhooks/subscribe'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/upload'
    | '/api/leads'
    | '/api/outreach'
    | '/api/upload'
    | '/api/auth/signin'
    | '/api/auth/signup'
    | '/api/dashboard/metrics'
    | '/api/leads/sync'
    | '/api/webhooks/subscribe'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  UploadRoute: typeof UploadRoute
  ApiLeadsRoute: typeof ApiLeadsRouteWithChildren
  ApiOutreachRoute: typeof ApiOutreachRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiDashboardMetricsRoute: typeof ApiDashboardMetricsRoute
  ApiWebhooksSubscribeRoute: typeof ApiWebhooksSubscribeRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outreach': {
      id: '/api/outreach'
      path: '/api/outreach'
      fullPath: '/api/outreach'
      preLoaderRoute: typeof ApiOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/subscribe': {
      id: '/api/webhooks/subscribe'
      path: '/api/webhooks/subscribe'
      fullPath: '/api/webhooks/subscribe'
      preLoaderRoute: typeof ApiWebhooksSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/sync': {
      id: '/api/leads/sync'
      path: '/sync'
      fullPath: '/api/leads/sync'
      preLoaderRoute: typeof ApiLeadsSyncRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/dashboard/metrics': {
      id: '/api/dashboard/metrics'
      path: '/api/dashboard/metrics'
      fullPath: '/api/dashboard/metrics'
      preLoaderRoute: typeof ApiDashboardMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiLeadsRouteChildren {
  ApiLeadsSyncRoute: typeof ApiLeadsSyncRoute
}

const ApiLeadsRouteChildren: ApiLeadsRouteChildren = {
  ApiLeadsSyncRoute: ApiLeadsSyncRoute,
}

const ApiLeadsRouteWithChildren = ApiLeadsRoute._addFileChildren(
  ApiLeadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  UploadRoute: UploadRoute,
  ApiLeadsRoute: ApiLeadsRouteWithChildren,
  ApiOutreachRoute: ApiOutreachRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiDashboardMetricsRoute: ApiDashboardMetricsRoute,
  ApiWebhooksSubscribeRoute: ApiWebhooksSubscribeRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
